import Vue from 'vue'
import {
  Button,
  Form,
  FormItem,
  Input,
  Checkbox,
  Message,
  Container,
  Aside,
  Header,
  Main,
  Footer,
  Row,
  Col,
  Menu,
  MenuItemGroup,
  MenuItem,
  Submenu,
  Divider,
  Avatar,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Badge,
  Tag,
  Breadcrumb,
  BreadcrumbItem,
  Table,
  TableColumn,
  Popover,
  Pagination,
  Loading,
  Dialog,
  Radio,
  RadioGroup,
  DatePicker,
  Upload,
  Popconfirm,
  Select,
  Option,
  Descriptions,
  DescriptionsItem,
  Image,
} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Checkbox)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Row)
Vue.use(Col)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Divider)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Badge)
Vue.use(Tag)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Popover)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(DatePicker)
Vue.use(Upload)
Vue.use(Popconfirm)
Vue.use(Select)
Vue.use(Option)
Vue.use(Descriptions)
Vue.use(DescriptionsItem)
Vue.use(Image)
Vue.use(Loading.directive)

Vue.prototype.$message = Message
